service: knowbe4-data-archiver

frameworkVersion: ^3.2.0

provider:
  name: aws
  runtime: go1.x
  stage: prod
  timeout: 600
  versionFunctions: false
  memorySize: 128
  region: us-east-1
  logRetentionInDays: 14
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Action:
        - 's3:PutObject'
        Resource:
          Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - ${env:AWS_S3_BUCKET}
            - '/*'
  s3:
    dataBucket:
      name: ${env:AWS_S3_BUCKET}
      versioningConfiguration:
        Status: Enabled
      lifecycleConfiguration:
        Rules:
        - Id: ExpirationRule
          Prefix: ''
          Status: Enabled
          ExpirationInDays: 15

package:
  patterns:
    - '!./**'
    - './bin/**'

functions:
  archiver:
    environment:
      API_BASE_URL: ${env:API_BASE_URL}
      API_AUTH_TOKEN: ${env:API_AUTH_TOKEN}
      AWS_S3_FILENAME: ${env:AWS_S3_FILENAME}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
    handler: bin/archiver
    events:
       # cron(Minutes Hours Day-of-month Month Day-of-week Year)
       # One of the day-of-month or day-of-week values must be a question mark (?)
       - schedule: cron(10 6 * * ? *)
